name: Reusable Echo Test

on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.message }}"
