name: Reusable Build Workflow
on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
      service-name:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - id: set-tag
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
      - run: echo "build placeholder"

